docs: include BNF under headings in input and output reference
canonical/sqlair pull request #166
Opened 2024-09-24 15:28 UTC by Aflynn50

Update the input and output reference to include the formal syntax under each form of expression.

2024-09-25 15:49 UTC, tmihoc requested changes
Summary of our in-person chat:

(1) It's good we're getting rid of this content in the how-to guides.

(2) It's good we're getting rid of the formal BNF schema in the reference -- you're right, without definitions for each expression it's useless. Please do still make the titles nominal, to better fit the Reference style (so, go from a verbal structure to a nominal structure, e.g., from "Output a single column" to "Output expression for a single column" (I'd favor this over briefer but less explicit titles such as "Single column").

Thanks for your patience with my questions on this!

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/input-expression-syntax.md
> +Syntax for the different input expressions is given in [Backus Naur
The* syntax

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/input-expression-syntax.md
> +In the syntax definitions, the following symbols have the given meanings:
the symbols have the meaning below:*

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/output-expression-syntax.md
> +Syntax for the different types of output expression is given in [Backus Naur
The* syntax

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/output-expression-syntax.md
> +Syntax for the different types of output expression is given in [Backus Naur
expressions*

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/input-expression-syntax.md
>  SQLair expressions can be either input expressions or output expressions. The
This sentence is undermining the goal announced in the title, which was to focus on input expressions. It takes us one step back. I'd remove it / move it to a higher level that links down to input and output.

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/input-expression-syntax.md
> +input expressions specify how SQLair will read the query arguments from the
will read x from y into z -- spelling everything out will make things a lot clearer / faster to consume.

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/input-expression-syntax.md
>  ## Input a query parameter
The titles are still how-to-guide-y. Makes me wonder about the structure of the doc.

2024-09-25 15:49 UTC, tmihoc commented on docs/reference/input-expression-syntax.md
>  For example in the snippet of SQL:
This is a snippet of SQLair, not SQL, right?

2024-09-26 14:00 UTC, Aflynn50 commented on docs/reference/input-expression-syntax.md
> +In the syntax definitions, the following symbols have the given meanings:
I think changing it to that would be misleading, saying "the symbols" implies these are all the symbols. These are really just the symbols that are defined outside of the grammer. 

I've changed it to: "the following symbols have the given meanings:" but I know this isn't idea either. I'm not really sure how to write it.

2024-09-26 16:10 UTC, Aflynn50 commented on docs/reference/input-expression-syntax.md
> +input expressions specify how SQLair will read the query arguments from the
Changed it to match that form, though it doesn't quite "read into" anything so much as pass to the database

2024-09-26 16:11 UTC, Aflynn50 commented on docs/reference/input-expression-syntax.md
>  For example in the snippet of SQL:
Its SQL with a SQLair expression, I've changed it to just say "in this snippet" to avoid confusion.

2024-09-27 10:42 UTC, tmihoc approved these changes
Looks as discussed, thanks!

2024-09-27 11:28 UTC, merged