Refector packages
canonical/sqlair pull request #29
Opened 2023-01-10 12:09 UTC by Aflynn50

This moves the contents of the `parse` and `typeinfo` packages to a new package called `expr`. All the functions changed are to be not exported so that they may be exported when needed.

The odd variable name has been changed here and there to avoid clashes with the new lowercase type.

2023-01-10 14:34 UTC, TheSignPainter98 commented on internal/expr/parts.go
> +// BypassPart represents a part of the expression that we want to pass to the
`s/BypassPart/bypassPart/`

2023-01-10 14:34 UTC, TheSignPainter98 commented on internal/expr/parts.go
> +	return "BypassPart[" + p.chunk + "]"
Also here, `s/BypassPart/bypassPart/`

2023-01-10 14:34 UTC, TheSignPainter98 commented on internal/expr/parts.go
> +	return fmt.Sprintf("InputPart[%+v]", p.source)
Capitalisation---should this be `inputPart[...]`?

2023-01-10 14:34 UTC, TheSignPainter98 commented on internal/expr/parts.go
> +	return fmt.Sprintf("OutputPart[%+v %+v]", p.source, p.target)
Likewise, should this be `outputPart`?

2023-01-11 08:23 UTC, Aflynn50 commented on internal/expr/parts.go
> +	return fmt.Sprintf("OutputPart[%+v %+v]", p.source, p.target)
Changed.

2023-01-11 08:23 UTC, Aflynn50 commented on internal/expr/parts.go
> +	return fmt.Sprintf("InputPart[%+v]", p.source)
Changed.

2023-01-11 08:23 UTC, Aflynn50 commented on internal/expr/parts.go
> +	return "BypassPart[" + p.chunk + "]"
Changed.

2023-01-11 08:23 UTC, Aflynn50 commented on internal/expr/parts.go
> +// BypassPart represents a part of the expression that we want to pass to the
Changed.

2023-01-11 16:34 UTC, niemeyer requested changes

2023-01-11 16:34 UTC, niemeyer commented on internal/expr/parser_test.go
> +package expr
PR looks good and seems ready to go in. As we discussed, this change is the only one that seems like a step backwards, as the tests were already using the public API.  If we revert this, we can merge the PR pretty much as-is and convert the other tests to also use the public API and poke holes through when actually required via the export_test.go pattern.

2023-01-12 15:37 UTC, niemeyer approved these changes
Thanks for the changes.

2023-01-12 15:37 UTC, merged