Mixed types output exprs
canonical/sqlair pull request #73
Opened 2023-05-18 15:40 UTC by Aflynn50

This PR allows output expressions to include a mixture of types.
e.g.:
`* AS (&Person.id, &Address.*, &Manager.name)`
or
`(name_1, id_1) AS (&Person.name, &Address.id)`

It also adds checks to make sure that the person hasn't output into the same field more than once (e.g. `* AS (&Person.*, &Person.name)`).

It includes PR #72

2023-06-13 09:43 UTC, niemeyer requested changes

2023-06-13 09:43 UTC, niemeyer commented on internal/expr/prepare.go
> +	if t := p.targetTypes[0]; t.name == "*" {
This PR looks nice in general. There's only an issue in the way these branches are being organized which would be good to improve. The branches don't actually do the verification to ensure that what they are handling is indeed what they believe to be, because they sort of trust the error handling doing far from here to be correct. Except, well, it might be checking different things, now or tomorrow, and this woud make the logic wrong and bogus in awkward ways. The mistake is so easy to make that it looks like it's been made already, as the above line is claiming to be handling a case that it's not (it only looks for the asterisk on the first member).

As a suggestion, move the case verifiaction logic into the actual branches they're supposed to protect, and inline the error checking logic as well so that it's clear what's supported and what's not, next to the actual logic supporting it.

2023-06-14 07:45 UTC, Aflynn50 commented on internal/expr/prepare.go
> +	if t := p.targetTypes[0]; t.name == "*" {
I've moved the logic of `CheckValidOutputExpr` into `PrepareOutput` and fixed the bug with multiple asterisk types. It looks a lot cleaner now and reads easier

2023-06-20 09:43 UTC, niemeyer approved these changes
Great, thank you!

2023-06-20 09:44 UTC, merged