Improve comments in `parser.go`
canonical/sqlair pull request #90
Opened 2023-07-25 10:19 UTC by Aflynn50

This PR corrects and improves on the language in some of the comments in `parser.go`. It also limits the line width to 80 columns.

2023-09-25 16:11 UTC, niemeyer requested changes
Thanks, lots of improvements there.

Only a few details.. mostly low importance nitpicks. Blocking mainly due to the documentation of the package external interface being a bit misleading (see the "uninitialized" bit).

2023-09-25 16:11 UTC, niemeyer commented on internal/expr/parser.go
> +// parseOutputExpression parsers a SQLair output expression. See the package
Typo ("parsers"). This comment can be dropped entirely, though, since it's literally reading the function name.

2023-09-25 16:11 UTC, niemeyer commented on internal/expr/parser.go
> +			}, true, nil
FWIW, this seems slightly less readable for some reason, probably because it's adding too much spacing in what's a small amount of code, and at the same time moving away the other results being returned (true and nil).

Compare that with this one, for instance:
```
part := &inputPart{sourceType: rn, raw: p.input[...]}
return part, true, nil
```

2023-09-25 16:11 UTC, niemeyer commented on internal/expr/parser.go
>  func (p *Parser) parseIdentifier() (string, bool) {
Something a bit curious here. What's the difference between a name and an identifier?  If there's none, we shoudn't have two names for them. If there is some, we should define what an identifier is in a way that is not just referring to it being a name.

2023-09-25 16:11 UTC, niemeyer commented on internal/expr/parser.go
> +// NewParser returns an uninitiated Parser.
What is an uninitialized Parser, in terms of the public API of this package?  Isn't it just NewParser => Parse?

2023-09-25 16:11 UTC, niemeyer commented on internal/expr/parser.go
> +// It is used for generating a ParsedExpr with the Parse method.
In general we don't document the methods on the type, since they have their own documentation. There are exceptions for types which need some handholding due to their complexity, but that doesn't seem to be the case here.

2023-10-02 19:27 UTC, Aflynn50 commented on internal/expr/parser.go
> +// It is used for generating a ParsedExpr with the Parse method.
Removed.

2023-10-02 19:36 UTC, Aflynn50 commented on internal/expr/parser.go
> +// NewParser returns an uninitiated Parser.
That's true, in terms of the API it doesn't mean much. I've removed this comment as there's really nothing to say in it that is not clear from the function name.

2023-10-02 19:38 UTC, Aflynn50 commented on internal/expr/parser.go
> +// parseOutputExpression parsers a SQLair output expression. See the package
Removed comment.

2023-10-02 19:53 UTC, Aflynn50 commented on internal/expr/parser.go
>  func (p *Parser) parseIdentifier() (string, bool) {
There is none, I've added a separate PR to change it #109.

2023-10-02 19:54 UTC, Aflynn50 commented on internal/expr/parser.go
> +			}, true, nil
Changed it back to being a one liner.

2023-12-04 09:27 UTC, closed without merging